{% set version = "20181111" %}

package:
  name: diff-match-patch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diff-match-patch/diff-match-patch-{{ version }}.tar.gz
  sha256: a809a996d0f09b9bbd59e9bbd0b71eed8c807922512910e05cbd3f9480712ddb

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - diff_match_patch

about:
  home: http://code.google.com/p/google-diff-match-patch/
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Diff Match Patch is a high-performance library in multiple languages that manipulates plain text'

extra:
  recipe-maintainers:
    - ocefpaf
    - ccordoba12
