travis:
  secure:
    BINSTAR_TOKEN: DqR/zeckyVmasBsUyfTMuMGnFekqVjo4/Mronw00Cssp/ZZ7JXeO3njjIR3Axq6nOJAAeqV2OEb6Gxd0iKN+JCTg9vv2MGAwG6DxSv2n36mTZ0Tgk4KmdmtonvHagId4r9/FOkOea5Qb4E7UBZgZWoXkwelwbwkEitkRAB/jGt1PAP4mlHmSUMBsY9IVRyqod5JkUwqPUwcfJDBLeWS+625ghCKodQiXRflksGRI4aaqWZkNXKxH7Ph6IbqP/7YzMyzPewgPWkT4/9XQFMMI3YD02i7l1oqsgN3z1XbZz8DM1ECqeN6A7/eV0PLtPddj7a10STVSRTmlPV0lvDERdrGp0nHyzBYep+N5ZsFrRBtCcu470Pn17WsIt0AypDln7tZV4Xc8EJncjJ3GCEsI/xghkH9HDIkm5JqYIZuJL17K1jmkzA1Q0hVtzxtfDQWesvC+BItKf9Slp7yuTHLZ93xKIMIBElCZFsNfMUBcJsseZKxlx9S6i/MRSr3h19hwPRYFxu4e/c7dd3XwJyEcoxRk/BubK/s/SAtWTrgMG+9LG6ZpZFIZWHCs9hEAM4BegGQLXPe3gxTM6tRnncUmqG7y3OH3zSZ/UdYdfuAI0djGVtYQKk/WTswCkUBxodgD/voUULR0OrDFT2dq+J9P3yLBvoK6YiPP2oHl0EqDjMA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
