travis:
  secure:
    BINSTAR_TOKEN: agoLpOGOh0slZkEm1IOwOqgYFskc8ZWHIMRGLIATsZg3WbhH46t4mIzVxvO31JySoTnQIPGmuV86T0EbRFrdDWQJMOLbHrOsvNOmV31V4SpZ/Dqv5VSn8CYp1CNU06TZEUmCMfA6rB2DvlOda9cFDuZMviJ7NAoBZx4EMm3gYDvUASeLBYv4HPKKXXbE3KgIqd3MRAo/rZlZ4nNdlJcAA2ZdZJOMnSw5Go3BcKqiJEEvkXKWiQ7Sg+aiEJntaH6+XKeTDdIZff1FUVuFZNOeSCFQ+pOcLHljWuT7sZTcd1OLbye7PAT1IdQ5r1fA944dbVUdnsuqolguyaVfM8kvrZtxJBiI2MrpbNGYOieB5CpaLoVctmu7F3lc1Ow7L2sj2lTAqzg+3Uz8yDuWivOcKpTJHORxBOvA5sdTqI9ndwUW3HZoD7naAVyxJUCA9wIimn33eSnKSVLB7XOJbEtfLXq6SessXDuElHVdKo4XWOhAxSidJIiG//FFJiQh/lFpScYv4CXuPcUV3zKiJDvMPOZ7C4eWqR62gd4UQmFEwumFZCUQzkQjAtUwazScBIQ9Mp44yfKMzm9ctxRLi0J9XerpSW08sXm3PjZnhFrV3+4ITP2gRTcMjARa3wrQH7GQXHuRi3CsxKB6h8bJOAVJuiuptLy8AavhZb6XT08DJuM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
